# Generated by Django 5.0.6 on 2024-09-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_resourcecategory_profile_country_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
