# Generated by Django 5.0.6 on 2024-08-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='delivery_time',
            new_name='shipping_on_time',
        ),
    ]
